#ifndef CK2TECHS_H
#define CK2TECHS_H_



enum TechTypes {
	// Military techs
	TECH_BOWS,
	TECH_LIGHT_ARMOUR,
	TECH_HEAVY_ARMOUR,
	TECH_INFANTRY_MELEE_WEAPONS,
	TECH_CAVALRY_MELEE_WEAPONS,
	TECH_SIEGE_EQUIPMENT,
	TECH_CASTLES,
	TECH_TACTICS,

	// Economy techs
	TECH_CASTLE_TAXES,
	TECH_CITY_TAXES,
	TECH_TEMPLE_TAXES,
	TECH_CASTLE_CONSTRUCTION,
	TECH_CITY_CONSTRUCTION,
	TECH_TEMPLE_CONSTRUCTION,
	TECH_FORTIFICATIONS_CONSTRUCTION,
	TECH_CONSTRUCTION,
	
	// Culture techs
	TECH_NOBLE_CUSTOMS,
	TECH_POPULAR_CUSTOMS,
	TECH_RELIGIOUS_CUSTOMS,
	TECH_MAJESTY,
	TECH_SPIRITUAL_ART,
	TECH_CULTURE_FLEX,
	TECH_RELIGION_FLEX,
	TECH_LEGALISM
};



#endif CK2TECHS_H_