#ifndef CK2TECHS_H
#define CK2TECHS_H_



enum olderTechTypes {
	// Military techs
	TECH_BOWS,
	TECH_LIGHT_ARMOUR,
	TECH_HEAVY_ARMOUR,
	TECH_INFANTRY_MELEE_WEAPONS,
	TECH_CAVALRY_MELEE_WEAPONS,
	TECH_SIEGE_EQUIPMENT_OLD,
	TECH_CASTLES,
	TECH_TACTICS,

	// Economy techs
	TECH_CASTLE_TAXES,
	TECH_CITY_TAXES,
	TECH_TEMPLE_TAXES,
	TECH_CASTLE_CONSTRUCTION_OLD,
	TECH_CITY_CONSTRUCTION_OLD,
	TECH_TEMPLE_CONSTRUCTION_OLD,
	TECH_FORTIFICATIONS_CONSTRUCTION_OLD,
	TECH_CONSTRUCTION_OLD,
	
	// Culture techs
	TECH_NOBLE_CUSTOMS_OLD,
	TECH_POPULAR_CUSTOMS_OLD,
	TECH_RELIGIOUS_CUSTOMS_OLD,
	TECH_MAJESTY_OLD,
	TECH_SPIRITUAL_ART,
	TECH_CULTURE_FLEX_OLD,
	TECH_RELIGION_FLEX,
	TECH_LEGALISM_OLD
};

enum newerTechTypes {
	// TECH_GROUP_MILITARY
	TECH_LIGHT_INFANTRY,
	TECH_HEAVY_INFANTRY,
	TECH_CAVALRY,
	TECH_SIEGE_EQUIPMENT,
	TECH_NAVAL,
	TECH_RECRUITMENT,

	//TECH_GROUP_ECONOMY
	TECH_CASTLE_CONSTRUCTION,
	TECH_CITY_CONSTRUCTION,
	TECH_TEMPLE_CONSTRUCTION,
	TECH_FORTIFICATIONS_CONSTRUCTION,
	TECH_TRADE_PRACTICES,
	TECH_CONSTRUCTION,

	//TECH_GROUP_CULTURE
	TECH_NOBLE_CUSTOMS,
	TECH_POPULAR_CUSTOMS,
	TECH_RELIGIOUS_CUSTOMS,
	TECH_MAJESTY,
	TECH_CULTURE_FLEX,
	TECH_LEGALISM
};



#endif CK2TECHS_H_